### ISSUE TITLE
Fail to run with multi terminals

### ISSUE THREAD

**Issue by omegaga** [ranxian/peloton-frontend#2]
When we run with multi terminals, multiple connections might try to access SQLite simultaneously, and SQLite will return an error when it is locked. In order to make it work in multi terminal mode, we need to add a lock from our side or do something to prevent this happening.

**Comment by sid1607** [comment]
For now, a coarse-grained mutex should suffice?

**Comment by sid1607** [comment]
Fixed. Set Sqlite to multi-threaded mode with "open" flags and used std mutex before begin and after commit
